apiVersion: apps/v1
kind: Deployment
metadata:
  name: announcementapi-deployment
  labels:
    app: announcementapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: announcementapi
  template:
    metadata:
      labels:
        app: announcementapi
    spec:
      containers:
        - name: announcementapi
          image: fitnessacr.azurecr.io/announcement-api:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: announcement_connection_string
            - name: EventBusSettings__HostAddress
              value: amqp://guest:guest@rabbitmq-service:5672
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: announcementapi-service
spec:
  type: LoadBalancer
  selector:
    app: announcementapi
  ports:
    - protocol: TCP
      port: 80           