apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: challengeapi-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: challengeapi-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization
  -----
  apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: announcementapi-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: announcementapi-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization