apiVersion: apps/v1
kind: Deployment
metadata:
  name: challengemongo-deployment
  labels:
    app: challenge-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-mongodb
  template:
    metadata:
      labels:
        app: challenge-mongodb
    spec:
      containers:
        - name: challenge-mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username                  
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: challengemongo-service
spec:
  selector:
    app: challenge-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27018