apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapi-deployment
  labels:
    app: chatapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatapi
  template:
    metadata:
      labels:
        app: chatapi
    spec:
      containers:
        - name: chatapi
          image: fitnessacr.azurecr.io/chat-api:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: chat_connection_string
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: chatapi-service
spec:
  type: LoadBalancer
  selector:
    app: chatapi
  ports:
    - protocol: TCP
      port: 80           