apiVersion: apps/v1
kind: Deployment
metadata:
  name: dietapi-deployment
  labels:
    app: dietapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dietapi
  template:
    metadata:
      labels:
        app: dietapi
    spec:
      containers:
        - name: dietapi
          image: fitnessacr.azurecr.io/diet-api:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: diet_connection_string
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: dietapi-service
spec:
  selector:
    app: dietapi
  ports:
    - protocol: TCP
      port: 80           