apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitnessapi-deployment
  labels:
    app: fitnessapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitnessapi
  template:
    metadata:
      labels:
        app: fitnessapi
    spec:
      containers:
        - name: fitnessapi
          image: fitnessacr.azurecr.io/fitness-api:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: fitness_connection_string
            - name: EventBusSettings__HostAddress
              value: amqp://guest:guest@rabbitmq-service:5672
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: fitnessapi-service
spec:
  type: LoadBalancer
  selector:
    app: fitnessapi
  ports:
    - protocol: TCP
      port: 80           