apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquiryapi-deployment
  labels:
    app: inquiryapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inquiryapi
  template:
    metadata:
      labels:
        app: inquiryapi
    spec:
      containers:
        - name: inquiryapi
          image: fitnessacr.azurecr.io/inquiry-api:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: inquiry_connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: inquiryapi-service
spec:
  selector:
    app: inquiryapi
  ports:
    - protocol: TCP
      port: 80           