apiVersion: apps/v1
kind: Deployment
metadata:
  name: inquriyapi-deployment
  labels:
    app: inquriyapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inquriyapi
  template:
    metadata:
      labels:
        app: inquriyapi
    spec:
      containers:
        - name: inquriyapi
          image: fitnessacr.azurecr.io/inquriyapi:v2
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: inquriyapi-service
spec:
  selector:
    app: inquriyapi
  ports:
    - protocol: TCP
      port: 80           