apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: QZF#4GU4rIcPPROh9cTv4Y^jJ##E
  mongo-root-password: ^f^H2M3Cg6LR%xY9@^Q00m9&zHXy#x!awPB!gKJ4hNX2n2Ad54