apiVersion: apps/v1
kind: Deployment
metadata:
  name: planapi-deployment
  labels:
    app: planapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planapi
  template:
    metadata:
      labels:
        app: planapi
    spec:
      containers:
        - name: planapi
          image: fitnessacr.azurecr.io/plan-api:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: plan_connection_string
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: planapi-service
spec:
  selector:
    app: planapi
  ports:
    - protocol: TCP
      port: 80           