apiVersion: apps/v1
kind: Deployment
metadata:
  name: profileapi-deployment
  labels:
    app: profileapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profileapi
  template:
    metadata:
      labels:
        app: profileapi
    spec:
      containers:
        - name: profileapi
          image: fitnessacr.azurecr.io/profile-api:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                  configMapKeyRef:
                    name: mongo-configmap
                    key: profile_connection_string
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: profileapi-service
spec:
  selector:
    app: profileapi
  ports:
    - protocol: TCP
      port: 80    
  type: LoadBalancer
