apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: ${ingress-config.ingress-service-config.announcement-service-name}
          servicePort: 80
        path: /announcement(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.challenge-service-name}
          servicePort: 80
        path: /challenge(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.chat-service-name}
          servicePort: 80
        path: /chat(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.diet-service-name}
          servicePort: 80
        path: /diet(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.fitness-service-name}
          servicePort: 80
        path: /fitness(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.inquiry-service-name}
          servicePort: 80
        path: /inquiry(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.notification-service-name}
          servicePort: 80
        path: /notification(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.plan-service-name}
          servicePort: 80
        path: /plan(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.profile-service-name}
          servicePort: 80
        path: /profile(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.survey-service-name}
          servicePort: 80
        path: /survey(/|$)(.*)
  - host: digitalfitness.eastus.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: ${ingress-config.ingress-service-config.announcement-service-name}
          servicePort: 80
        path: /announcement(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.challenge-service-name}
          servicePort: 80
        path: /challenge(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.chat-service-name}
          servicePort: 80
        path: /chat(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.diet-service-name}
          servicePort: 80
        path: /diet(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.fitness-service-name}
          servicePort: 80
        path: /fitness(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.inquiry-service-name}
          servicePort: 80
        path: /inquiry(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.notification-service-name}
          servicePort: 80
        path: /notification(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.plan-service-name}
          servicePort: 80
        path: /plan(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.profile-service-name}
          servicePort: 80
        path: /profile(/|$)(.*)
      - backend:
          serviceName: ${ingress-config.ingress-service-config.survey-service-name}
          servicePort: 80
        path: /survey(/|$)(.*)