apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: announcementapi-service
          servicePort: 80
        path: /announcement(/|$)(.*)
      - backend:
          serviceName: challengeapi-service
          servicePort: 80
        path: /challenge(/|$)(.*)
      - backend:
          serviceName: chatapi-service
          servicePort: 80
        path: /chat(/|$)(.*)
      - backend:
          serviceName: dietapi-service
          servicePort: 80
        path: /diet(/|$)(.*)
      - backend:
          serviceName: fitnessapi-service
          servicePort: 80
        path: /fitness(/|$)(.*)
      - backend:
          serviceName: inquiryapi-service
          servicePort: 80
        path: /inquiry(/|$)(.*)
      - backend:
          serviceName: notificationapi-service
          servicePort: 80
        path: /notification(/|$)(.*)
      - backend:
          serviceName: planapi-service
          servicePort: 80
        path: /plan(/|$)(.*)
      - backend:
          serviceName: profileapi-service
          servicePort: 80
        path: /profile(/|$)(.*)
      - backend:
          serviceName: surveyapi-service
          servicePort: 80
        path: /survey(/|$)(.*)
  - host: digitalfitness.eastus.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: announcementapi-service
          servicePort: 80
        path: /announcement(/|$)(.*)
      - backend:
          serviceName: challengeapi-service
          servicePort: 80
        path: /challenge(/|$)(.*)
      - backend:
          serviceName: chatapi-service
          servicePort: 80
        path: /chat(/|$)(.*)
      - backend:
          serviceName: dietapi-service
          servicePort: 80
        path: /diet(/|$)(.*)
      - backend:
          serviceName: fitnessapi-service
          servicePort: 80
        path: /fitness(/|$)(.*)
      - backend:
          serviceName: inquiryapi-service
          servicePort: 80
        path: /inquiry(/|$)(.*)
      - backend:
          serviceName: notificationapi-service
          servicePort: 80
        path: /notification(/|$)(.*)
      - backend:
          serviceName: planapi-service
          servicePort: 80
        path: /plan(/|$)(.*)
      - backend:
          serviceName: profileapi-service
          servicePort: 80
        path: /profile(/|$)(.*)
      - backend:
          serviceName: surveyapi-service
          servicePort: 80
        path: /survey(/|$)(.*)